#!/bin/bash

CONTAINER_REGISTRY="kakalin"
CONTAINER_REPOSITORY="qt"
CONTAINER_TAG="5.12.0"

docker build --rm -t $CONTAINER_REGISTRY/$CONTAINER_REPOSITORY:$CONTAINER_TAG .
docker push $CONTAINER_REGISTRY/$CONTAINER_REPOSITORY:$CONTAINER_TAG
